Repository lino62U/online-election-v2.0, pull requests merged in 2023-12, with the labels that each got.

#18 fix function decodeToken in front
  frontend/src/utils/decodeToken.tsx
Labels: refactoring, minor

#20 Feature Auth Token Filter
  src/main/java/org/system/onlineelection/infrastructure/adapter/jwt/AuthTokenFilter.java
Labels: refactoring, blocker

#25 Fix critical error in JwtUtils
  pom.xml
  src/main/java/org/system/onlineelection/infrastructure/adapter/jwt/JwtUtils.java
  src/test/java/org/system/onlineelection/JwtUtilsTest.java
Labels: refactoring, critical

#29 Fix cors
  src/test/java/org/system/onlineelection/WebConfigTest.java
Labels: documentation

#31 Fix hash code in userDetailImpl
  src/main/java/org/system/onlineelection/application/service/UserDetailsImpl.java
  src/test/java/org/system/onlineelection/UserDetailsImplTest.java
Labels: refactoring, minor

#32 create modal4
  frontend/src/pages/votacion/Votacion.tsx
Labels: bug, enhancement

#34 Feature auth token filter
  src/main/java/org/system/onlineelection/infrastructure/adapter/jwt/AuthTokenFilter.java
  src/main/java/org/system/onlineelection/infrastructure/controller/AuthController.java
  src/main/resources/application.properties
Labels: bug

#36 Dev
  frontend/src/App.tsx
  frontend/src/components/GoToHome.tsx
  frontend/src/components/Model.tsx
  frontend/src/config/axios.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/services/fetchCandidates.ts
  frontend/src/pages/login/Login.tsx
  frontend/src/pages/login/services/loginService.ts
  frontend/src/pages/register/Register.tsx
  frontend/src/pages/register/interfaces/register.interface.ts
  frontend/src/pages/register/services/registerService.ts
  frontend/src/pages/resultado/Resultado.tsx
  frontend/src/pages/resultado/services/fetchResultPartys.ts
  frontend/src/pages/resultado/services/saveResultVotation.ts
  frontend/src/pages/votacion/Votacion.tsx
  frontend/src/pages/votacion/components/Model.tsx
  frontend/src/pages/votacion/services/fetchPartys.ts
  frontend/src/pages/votacion/services/sendVote.ts
  frontend/src/utils/decodeToken.tsx
  pom.xml
  src/main/java/org/system/onlineelection/application/mapper/EntityMapping.java
  src/main/java/org/system/onlineelection/application/mapper/PersonDto.java
  src/main/java/org/system/onlineelection/application/mapper/VoteDto.java
  src/main/java/org/system/onlineelection/application/service/AuthService.java
  src/main/java/org/system/onlineelection/application/service/UserDetailsImpl.java
  src/main/java/org/system/onlineelection/domain/model/PoliticalParty.java
  src/main/java/org/system/onlineelection/infrastructure/adapter/jwt/AuthTokenFilter.java
  src/main/java/org/system/onlineelection/infrastructure/adapter/jwt/JwtUtils.java
  src/main/java/org/system/onlineelection/infrastructure/config/WebSecurityConfig.java
  src/main/java/org/system/onlineelection/infrastructure/controller/AuthController.java
  src/main/resources/application.properties
  src/test/java/org/system/onlineelection/JwtUtilsTest.java
  src/test/java/org/system/onlineelection/MainApplicationTests.java
  src/test/java/org/system/onlineelection/UserDetailsImplTest.java
  src/test/java/org/system/onlineelection/WebConfigTest.java
Labels: enhancement

#48 Implement Microservice eureka
  microservice-eureka/.gitignore
  microservice-eureka/.mvn/wrapper/maven-wrapper.jar
  microservice-eureka/.mvn/wrapper/maven-wrapper.properties
  microservice-eureka/mvnw
  microservice-eureka/mvnw.cmd
  microservice-eureka/pom.xml
  microservice-eureka/src/main/java/com/microservice/eureka/MicroserviceEurekaApplication.java
  microservice-eureka/src/main/resources/application.yml
  microservice-eureka/src/main/resources/banner.txt
  microservice-eureka/src/test/java/com/microservice/eureka/MicroserviceEurekaApplicationTests.java
Labels: enhancement

#50 Implementation microservice auth
  microservice-auth/.gitignore
  microservice-auth/.mvn/wrapper/maven-wrapper.jar
  microservice-auth/.mvn/wrapper/maven-wrapper.properties
  microservice-auth/mvnw
  microservice-auth/mvnw.cmd
  microservice-auth/pom.xml
  microservice-auth/src/main/java/com/microservice/auth/MicroserviceAuthApplication.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/CandidateDto.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/ERole.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/EntityMapping.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/ResultDto.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/RoleEntityDto.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/VoteDto.java
  microservice-auth/src/main/java/com/microservice/auth/application/mapper/VotingResult.java
  microservice-auth/src/main/java/com/microservice/auth/application/services/AuthService.java
  microservice-auth/src/main/java/com/microservice/auth/application/services/UserDetailsImpl.java
  microservice-auth/src/main/java/com/microservice/auth/application/services/UserDetailsServiceImpl.java
  microservice-auth/src/main/java/com/microservice/auth/domain/model/Person.java
  microservice-auth/src/main/java/com/microservice/auth/domain/port/output/AuthServicePort.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/AdminEntity.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/CandidateEntity.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/ERole.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/ElectorEntity.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/PersonEntity.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/PoliticalPartyEntityDto.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/RoleEntity.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/entity/VoteEntity.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/jwt/AuthEntryPointJwt.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/jwt/AuthTokenFilter.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/jwt/JwtUtils.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/payload/AuthResponse.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/payload/JwtResponse.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/payload/LoginRequest.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/payload/RegisterRequest.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/payload/RoleResponse.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/adapter/payload/UserDto.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/config/ApplicationConfig.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/config/CorsConfig.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/config/WebSecurityConfig.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/controller/AuthController.java
  microservice-auth/src/main/java/com/microservice/auth/infrastructure/repository/PersonRepository.java
  microservice-auth/src/main/resources/application.yml
  microservice-auth/src/main/resources/banner.txt
  microservice-auth/src/test/java/com/microservice/auth/MicroserviceAuthApplicationTests.java
  microservice-eureka/microservice-eureka.iml
  microservice-eureka/target/classes/application.yml
  microservice-eureka/target/classes/banner.txt
  microservice-eureka/target/classes/com/microservice/eureka/MicroserviceEurekaApplication.class
Labels: enhancement
